language: go

go:
  - 1.7.x
  - 1.8.x
  - master

services:
  - mysql

addons:
  apt:
    sources:
      - sourceline: 'ppa:masterminds/glide'
    packages:
      - glide

before_install:
  - export GOPATH=$HOME

install:
  - make -C backend deps
  - make -C backend initdb
  - make -C backend inittest

script:
  - go vet -n -x $(glide nv -d ./backend | grep ./ | cat)
  - go test -v $(glide nv -d ./backend)

notifications:
  email: false
  slack:
    secure: IoY4g3/xHgTKz4QtYFbSK7i7GseiFH3QiPnKThLIHFFqwDcStzzKtR2VUT0e8wDeNWY3qYgJmeZTlKVFjcBhwTUeuqKI76/jHOHLcG5M+acANTfiGIqqwglQxyRFWqwsIL0OAJoc+irbvIPfQM8nBY5kesx+bBWQ7SFQlfNJ44wdx/PIXVOIi8LRWqGmqlWTNX3PhEdC+Rji+5lha9L9IyTwLCeLSYEtqGc2avxiMJUNaVZtB4CQqLOB0o/jAgx00QKe/qVvfVXsqYY2jY9psvT/WmC5m3mk6mX4BxfGT/L8pma154U0D8Ez06NuGXn4T8v4Hh5QqUTighvpNTdStTlH+lg8p4MoBiOK/5mZ8/IKmQRQNt54SpxylQGcRQbO2+j6VHZKBdmj2pkxKgQ5I7fcbD/AGTl8PROpeN0T1Rv6wtbYkcQ4qbho13GiuJdQw5A1fOh5h7A5UaYHfCXOVyiWBmrkSN0B/y5UEwBCCVCHDxJXRqtV0oRs8leAbO87naslyIlAtRLcRVF5uGnDtrhg0aF3uoUVPXUPcbrxY6Xjl3avwWJOq0yoWgC2kTJJNlhb8ReRHpWi7lVke/IKplzGY5JojXRCE96jm1c+Av+0nywnjX7EMbEO5EatSib6Ur4rJr/t1YMcb6opMC+YzbQOdQ6rodH4cYSQyRMnuvI=
